service: node-aws-lambda-crud
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:099376587684:table/Tokens 

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  tokens:
    handler: src/controller/tokens.token
    events:
      - httpApi:
          path: /tokens
          method: post
  getToken:
    handler: src/controller/getToken.getToken
    events:
      - httpApi:
          path: /token/{token}
          method: get
 
resources:
  Resources:
    Tokens:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Tokens
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH